In [34]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv("DateFruit_Dataset.csv")
df.head()   # 34 features, 1 category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [36]:
df.isnull().sum()   # no NULL value => no need of data cleaning

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [37]:
df.shape

(898, 35)

In [38]:
X=df.drop("Class",axis=1)
y=df["Class"]

In [39]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [40]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)

In [41]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [42]:
# In Output layer of ANN we will have 7 Neurons, as in Multi-class classification the No. of neurons in output layer is equal to No. of categories in class

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [43]:
X_train
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108
332,156030,1566.9790,595.6793,384.2388,0.7641,445.7169,0.9118,171132,0.6319,1.5503,...,-0.3529,2.5952,2.3904,2.6668,-33837977600,-33563627520,-25646532608,70.7212,71.3609,63.4659

In [44]:
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

### ANN

In [45]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [46]:
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)      # for Multi-class classification in ANN, the loss function => cross entropy loss(it expects target values in long data type)

X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [47]:
train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [48]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)   # shuffle is very important for training loader, y values are set in the ascending order, if we directly split then training for some specific classes and some specific values which may not be present in the training dataset due to the split
test_loader=DataLoader(test_dataset, batch_size=32)

In [49]:
# Build our model

class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()

        self.model=nn.Sequential(
            # 1st Layer
            nn.Linear(X.shape[1],64),
            nn.ReLU(),

            # 2nd Layer
            nn.Linear(64,64),
            nn.ReLU(),

            # Output Layer
            nn.Linear(64,7),
        )

    def forward(self,x):
        return self.model(x)

In [50]:
model=ANN()

# loss & optim
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [51]:
# Training the NN

# this time we will not perform validation because we don't have much bigger dataset, we will direct apply training and calculate training_loss for every epoch

epochs=100
for epoch in range(epochs):
    model.train()

    running_loss=0.0

    for xb,yb in train_loader:
        optimizer.zero_grad()

        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step()   # params update

        running_loss+=loss

    training_loss=running_loss/len(train_loader)

    print(f"epoch={epoch+1}/{epochs}, loss={training_loss}")

epoch=1/100, loss=1.7722710371017456
epoch=2/100, loss=1.1776646375656128
epoch=3/100, loss=0.7329760193824768
epoch=4/100, loss=0.5260715484619141
epoch=5/100, loss=0.4248124957084656
epoch=6/100, loss=0.3619682490825653
epoch=7/100, loss=0.32206249237060547
epoch=8/100, loss=0.291006863117218
epoch=9/100, loss=0.2694343030452728
epoch=10/100, loss=0.2495533525943756
epoch=11/100, loss=0.23599544167518616
epoch=12/100, loss=0.21959547698497772
epoch=13/100, loss=0.21180115640163422
epoch=14/100, loss=0.209822878241539
epoch=15/100, loss=0.2027541846036911
epoch=16/100, loss=0.18966643512248993
epoch=17/100, loss=0.17276139557361603
epoch=18/100, loss=0.1753314882516861
epoch=19/100, loss=0.16860243678092957
epoch=20/100, loss=0.16772571206092834
epoch=21/100, loss=0.1572152078151703
epoch=22/100, loss=0.15264178812503815
epoch=23/100, loss=0.15878188610076904
epoch=24/100, loss=0.14741308987140656
epoch=25/100, loss=0.1381032019853592
epoch=26/100, loss=0.14394040405750275
epoch=27/100, loss=0.13399751484394073
epoch=28/100, loss=0.144428089261055
epoch=29/100, loss=0.1282297819852829
epoch=30/100, loss=0.12356697767972946
epoch=31/100, loss=0.1304762065410614
epoch=32/100, loss=0.1246674656867981
epoch=33/100, loss=0.12055205553770065
epoch=34/100, loss=0.11164765805006027
epoch=35/100, loss=0.11772295832633972
epoch=36/100, loss=0.10708356648683548
epoch=37/100, loss=0.10734148323535919
epoch=38/100, loss=0.10381206125020981
epoch=39/100, loss=0.10639457404613495
epoch=40/100, loss=0.10030283778905869
epoch=41/100, loss=0.0948675274848938
epoch=42/100, loss=0.09853503853082657
epoch=43/100, loss=0.10060729086399078
epoch=44/100, loss=0.0945589616894722
epoch=45/100, loss=0.09074082225561142
epoch=46/100, loss=0.08617297559976578
epoch=47/100, loss=0.0829714760184288
epoch=48/100, loss=0.08385449647903442
epoch=49/100, loss=0.08008457720279694
epoch=50/100, loss=0.08603040128946304
epoch=51/100, loss=0.07552583515644073
epoch=52/100, loss=0.07912281155586243
epoch=53/100, loss=0.07398699969053268
epoch=54/100, loss=0.0740877240896225
epoch=55/100, loss=0.07137607038021088
epoch=56/100, loss=0.07116591930389404
epoch=57/100, loss=0.07218849658966064
epoch=58/100, loss=0.06654229015111923
epoch=59/100, loss=0.06295163929462433
epoch=60/100, loss=0.05979685112833977
epoch=61/100, loss=0.06131324544548988
epoch=62/100, loss=0.06310268491506577
epoch=63/100, loss=0.06059636175632477
epoch=64/100, loss=0.05496414378285408
epoch=65/100, loss=0.055522896349430084
epoch=66/100, loss=0.059370171278715134
epoch=67/100, loss=0.05737308785319328
epoch=68/100, loss=0.05217486992478371
epoch=69/100, loss=0.04902675747871399
epoch=70/100, loss=0.054047513753175735
epoch=71/100, loss=0.048013053834438324
epoch=72/100, loss=0.045201223343610764
epoch=73/100, loss=0.04607248306274414
epoch=74/100, loss=0.04722101613879204
epoch=75/100, loss=0.04644327610731125
epoch=76/100, loss=0.04426306113600731
epoch=77/100, loss=0.0413193553686142
epoch=78/100, loss=0.041340891271829605
epoch=79/100, loss=0.042001716792583466
epoch=80/100, loss=0.04113081097602844
epoch=81/100, loss=0.0426359623670578
epoch=82/100, loss=0.035281047224998474
epoch=83/100, loss=0.03371034562587738
epoch=84/100, loss=0.03821044787764549
epoch=85/100, loss=0.036373335868120193
epoch=86/100, loss=0.03238808363676071
epoch=87/100, loss=0.0310953538864851
epoch=88/100, loss=0.032606061547994614
epoch=89/100, loss=0.029432522132992744
epoch=90/100, loss=0.02811833657324314
epoch=91/100, loss=0.03321075811982155
epoch=92/100, loss=0.03186875954270363
epoch=93/100, loss=0.03481266275048256
epoch=94/100, loss=0.028551798313856125
epoch=95/100, loss=0.026524363085627556
epoch=96/100, loss=0.02964351512491703
epoch=97/100, loss=0.02981673553586006
epoch=98/100, loss=0.027934983372688293
epoch=99/100, loss=0.025127358734607697
epoch=100/100, loss=0.023840153589844704

In [61]:
# we can select our best model based on the training loss or we can also select the last model(last ANN params)

# Evaluation
model.eval()    # put the model in evaluation mode --> now parameters are fixed, no learning on the basis of testing data

total=0        # total values in our testing data
correct=0      # how many of total it predicted correct

with torch.no_grad():
    for xb,yb in test_loader:
        outputs=model(xb)   # [0.2,0.5,1.3,-0.5....] -> 7 values will be produuced in this tensor
        # apply softmax on these set of values which will find the maximum value among them
        # here, in this set of values the output category ans will be 2 -> predicted label
        _, predicted=torch.max(outputs,1)  # torch.max(outputs,1) returns two values max_value, index(predicted) we don't need the maximum value so we indicate it with _
        correct += (predicted==yb).sum().item()   # for all batches
        total += yb.size(0)   # yb.size() returns actual samples in each batch

print("total Values:",total)
print("correct Values:",correct)


print("Accuracy score:",(correct/total)*100)

total Values: 180
correct Values: 169
Accuracy score: 93.88888888888889

In [58]:
y_train.shape
y_test.shape

(180,)

In [ ]:
# we are taking yb.size() not the 32 as it may happen that there are not 32 values in last batch 180 % 32 = 20 values in last batch