In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("IMDB Dataset.csv")

In [5]:
df.shape

(50000, 2)

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(49582, 2)

# PreProcessing

### 1. converting to lower case values

In [10]:
df["review"]=df["review"].str.lower()

### 2. Removing the URLs

In [11]:
import re                # regular expressions

# sample_text="abc is the word, abc" # abc => xyz

# # re.sub(patten, repl, string, count=0, flags=0)
# new_text=re.sub("abc","xyz",sample_text)      # ( define the pattern we want to find,  another pattern to be replaced with that pattern, document in which we have to identify the pattern)

In [12]:
def remove_urls(text):
    text=re.sub(r"http\S+","",text) # (pattern, repl, string) eg-https://www.google.com
    return text
    
df["review"]=df["review"].apply(remove_urls)

### 3. Removing Punctuations

In [13]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text) 
    return text

df["review"]=df["review"].apply(remove_punctuations)

### 4. Removing HTML

In [14]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text) 
    return text

df["review"]=df["review"].apply(remove_html)

### 5. Removing the Stop words

In [15]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\arnav\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\arnav\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arnav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [17]:
# sample_text="I love coding in python!"
# tokens=word_tokenize(sample_text)

In [19]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text=text.replace(word,"")
    return text       

df["review"]=df["review"].apply(remove_stopwords)

In [20]:
df.head()

                                              review sentiment
0  e    revewers  nte   wtchg  1 oz epoe   hooke ...  positive
1   wderful ltle prducti br br  filming technique...  positive
2   hugh h   werful w  pen me    h ummer weeken n...  positive
3  bcy   fly   e boy jke hk   zobe   cloe   pn  f...  negative
4  peer me love   i     vu unng film  wch mr mei ...  positive

### 6. Stemming

In [21]:
# running => run
# played => play

# Porter Stemming

from nltk.stem import PorterStemmer

In [22]:
def Stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]

    tokens=word_tokenize(text)
    for token in tokens:
        stemmed_token=ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"]=df["review"].apply(Stemming)

In [23]:
df.head()

                                              review sentiment
0  e revew nte wtchg 1 oz epo hook rght exctl hpp...  positive
1  wder ltle prducti br br film techniqu unssum l...  positive
2  hugh h wer w pen me h ummer weeken ng n r cne ...  positive
3  bci fli e boy jke hk zobe cloe pn fghg ebr br ...  negative
4  peer me love i vu unng film wch mr mei fer u v...  positive

### 7. Encoding

In [24]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [25]:
y=df["sentiment"]

In [26]:
y   # positive sentiments -> 1, negative sentiments -> 0

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [27]:
df.head()

                                              review  sentiment
0  e revew nte wtchg 1 oz epo hook rght exctl hpp...          1
1  wder ltle prducti br br film techniqu unssum l...          1
2  hugh h wer w pen me h ummer weeken ng n r cne ...          1
3  bci fli e boy jke hk zobe cloe pn fghg ebr br ...          0
4  peer me love i vu unng film wch mr mei fer u v...          1

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=5000)
X=tf.fit_transform(df["review"])

In [29]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316102 stored elements and shape (49582, 5000)>

In [30]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316102 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3962)	0.07314282300609996
  (0, 4935)	0.14950938847188663
  (0, 3426)	0.4698640965354833
  (0, 1491)	0.16244209325938672
  (0, 2283)	0.07923919927127605
  (0, 3978)	0.15178703358489806
  (0, 1629)	0.09605370040119345
  (0, 2328)	0.059413310971479213
  (0, 264)	0.08228624418462524
  (0, 1935)	0.16942996486293824
  (0, 4314)	0.05899315405421301
  (0, 4166)	0.05729696611296147
  (0, 4709)	0.2770729449171833
  (0, 4201)	0.08362913949999684
  (0, 2065)	0.03483596838994734
  (0, 4215)	0.2641922463354714
  (0, 1940)	0.07943834322627065
  (0, 2199)	0.0901262901744208
  (0, 3802)	0.043113833333287284
  (0, 3816)	0.08133575442157247
  (0, 3924)	0.09368624090115052
  (0, 4125)	0.07568854099337527
  (0, 4204)	0.08005374587498516
  (0, 614)	0.0977245052147425
  (0, 4605)	0.06771933259930923
  :	:
  (49581, 3013)	0.6322832966347672
  (49581, 3600)	0.07708762613869068
  (49581, 256)	0.08283729185906373
  (49581, 4123)	0.09153434378227822
  (49581, 427)	0.06226178108370525
  (49581, 515)	0.10642698607162616
  (49581, 4632)	0.08094985102172797
  (49581, 2616)	0.13341204943087576
  (49581, 1505)	0.1205769318065429
  (49581, 2311)	0.10627919032226671
  (49581, 2656)	0.08997373475343341
  (49581, 4541)	0.12696239513563262
  (49581, 367)	0.1321628987820879
  (49581, 4880)	0.2404904575119017
  (49581, 4703)	0.13086508465005006
  (49581, 621)	0.1297007062963437
  (49581, 4742)	0.10285633187856055
  (49581, 1492)	0.12072046070109305
  (49581, 3948)	0.17366105732823034
  (49581, 2603)	0.17858909593995048
  (49581, 2343)	0.14429517003247952
  (49581, 523)	0.1262025996828523
  (49581, 4973)	0.15568356974471215
  (49581, 2087)	0.1760027848307958
  (49581, 3624)	0.1715216241299442

## Dataset & DataLoaders

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [32]:
X_train.shape

(39665, 5000)

In [33]:
X_test.shape

(9917, 5000)

In [34]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [35]:
X_train   # presently it is a sparse matrix, we don't use sparse matrix directly for our dataset 
# we first have to convert sparse matrix into a numpy array

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2655143 stored elements and shape (39665, 5000)>

In [36]:
X_train=X_train.toarray()
X_test=X_test.toarray()

In [39]:
train_set=TensorDataset(            # to create tensor
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set=TensorDataset(            # to create tensor
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [40]:
train_loader=DataLoader(train_set, shuffle=True, batch_size=64)
test_loader=DataLoader(test_set, shuffle=True, batch_size=64)

### Build our RNN

In [45]:
import torch.nn as nn
import torch.optim as optim

In [46]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size=hidden_size
        self.num_layers=num_layers

 # to create RNN, we don't need to write the code from scratch as it already exist in the pyTorch, it already have functionality to build RNN
        # RNN layer
        self.rnn=nn.RNN(input_size, hidden_size, num_layers, batch_first=True)   # batch_first=True, by doing this we don't need to perform various reshape operations
 # models in pytorch by default expects input as (seq_length, batch_size, input_size) , seq_length => number of time steps(no. of tokens)

        # fully connected layer
        self.fc=nn.Linear(hidden_size,1)    # (input,output), it is a many to one architecture

    def forward(self,x):
        # optional;  by default h0 is initialized with 0
        # hidden layer shape => (num of layers, batch size, hidden layer size) -> matrix of zeroes
        h0=torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x,h0)  
        # 1st value=hidden state of all timesteps => (batch, seq_len, hidden size)
        # 2nd value=final hidden state of all timesteps
        # in the output we don't need to use all hidden states from that complete data we only need

        out=self.fc(out[:, -1,:])
        return out

In [48]:
input_size=X_train.shape[1]

model=RNN(input_size)

criterion=nn.BCELoss() # binary cross entropy loss
optimizer=optim.Adam(model.parameters())

## Training the RNN

In [51]:
# in pytorch we have two important functions -> unsqueeze and squeeze
# unsqueeze -> bring one additional dimension in the data
# squeeze -> reduce one dimension in the data

epochs=10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb=Xb.unsqueeze(1)   # add singleton direction

        outputs=model(Xb)    # (batch_size,1) => 2D value to bring it in 1D we will use squeeze
        # before adding Xb in the loss functions we have to convert them in the probabilities to do so, we will use the sigmoid function

        outputs = torch.sigmoid(outputs.squeeze())  # (batch_size,) => probability

        loss=criterion(outputs, yb)  # compute loss
        loss.backward()  # backpropagation

        optimizer.step()   # weights update
    print(f"epoch={epoch+1}/{epochs} and loss={loss.item()}")

epoch=1/10 and loss=0.36221998929977417
epoch=2/10 and loss=0.260597825050354
epoch=3/10 and loss=0.16862055659294128
epoch=4/10 and loss=0.3890710473060608
epoch=5/10 and loss=0.41871780157089233
epoch=6/10 and loss=0.27974221110343933
epoch=7/10 and loss=0.2728308141231537
epoch=8/10 and loss=0.34949252009391785
epoch=9/10 and loss=0.4132368564605713
epoch=10/10 and loss=0.33884507417678833

In [53]:
# in RNN we have the problem of frequent vanishing gradient which we can observe by seeing loss values

# evaluate

model.eval()

with torch.no_grad():
    correct_vals=0
    total_vals=0

    for Xb,yb in test_loader:
        Xb=Xb.unsqueeze(1)

        outputs=model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        total_vals += yb.size(0)
        correct_vals += (predicted==yb).sum().item()

    print(f"accuracy = {correct_vals/total_vals*100}")

accuracy = 82.20227891499445